name: build

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
  
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
  
      - name: Install dependencies
        run: pnpm install
  
      - name: Build project
        run: pnpm build
  
      - name: publish to build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: ./dist
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          MESSAGE: "Build status successfull"
  
      - name: Checkout build branch
        uses: actions/checkout@v4.1.1
        with:
          ref: "build"
